// <auto-generated />
using System;
using InvenLock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvenLock.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230130020720_AjustandoRestricoesTresEntidades")]
    partial class AjustandoRestricoesTresEntidades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvenLock.Models.ConsertoEquip", b =>
                {
                    b.Property<int>("ConsertoEquipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsertoEquipId"));

                    b.Property<string>("DescProblema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipamentoId")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("OcorrenciaId")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<int>("SituacaoConserto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ConsertoEquipId");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("OcorrenciaId")
                        .IsUnique();

                    b.ToTable("ConsertoEquip");
                });

            modelBuilder.Entity("InvenLock.Models.Equipamento", b =>
                {
                    b.Property<string>("EquipamentoId")
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("DataEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValue(new DateTime(2023, 1, 29, 23, 7, 20, 792, DateTimeKind.Local).AddTicks(7556));

                    b.Property<string>("DescEquipamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituacaoEquip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TipoEquip")
                        .HasColumnType("int");

                    b.HasKey("EquipamentoId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("InvenLock.Models.Ocorrencia", b =>
                {
                    b.Property<string>("OcorrenciaId")
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("DataFimOcorrencia")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("DataOcorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValue(new DateTime(2023, 1, 29, 23, 7, 20, 792, DateTimeKind.Local).AddTicks(7092));

                    b.Property<string>("DescOcorrencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionarioCPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituacaoConserto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OcorrenciaId");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("InvenLock.Models.ConsertoEquip", b =>
                {
                    b.HasOne("InvenLock.Models.Equipamento", "Equipamento")
                        .WithMany("ConsertoEquips")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvenLock.Models.Ocorrencia", "Ocorrencia")
                        .WithOne("ConsertoEquip")
                        .HasForeignKey("InvenLock.Models.ConsertoEquip", "OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Ocorrencia");
                });

            modelBuilder.Entity("InvenLock.Models.Equipamento", b =>
                {
                    b.Navigation("ConsertoEquips");
                });

            modelBuilder.Entity("InvenLock.Models.Ocorrencia", b =>
                {
                    b.Navigation("ConsertoEquip")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
